name: Deploy to staging
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Continous Deployment
        # env:
        #   PAT: ${{ secrets.PAT }}
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} &> ~/ssh_key
          ssh -i  ~/ssh_key avtechnosys02@35.193.96.53
          git pull origin main
          pnpm install
          pnpm build
          pm2 restart all
